# Generated by Django 6.1 on 2026-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('facturacion_arca', 'Facturación ARCA'), ('whatsapp', 'Envío WhatsApp'), ('venta_nube', 'Venta a nube'), ('producto_nube', 'Producto a nube'), ('cliente_nube', 'Cliente a nube')], max_length=50)),
                ('datos', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('intentos', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Operación Pendiente',
                'verbose_name_plural': 'Operaciones Pendientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SincronizacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('operaciones_procesadas', models.IntegerField(default=0)),
                ('operaciones_exitosas', models.IntegerField(default=0)),
                ('operaciones_fallidas', models.IntegerField(default=0)),
                ('duracion_segundos', models.FloatField(default=0)),
                ('mensaje', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-fecha'],
            },
        ),
    ]
