# Generated by Django 6.1 on 2026-08-18 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='creado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='es_remito_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_arca',
            field=models.CharField(choices=[('no_generado', 'No Generado'), ('pendiente', 'Pendiente'), ('generado', 'Generado'), ('error', 'Error'), ('anulado', 'Anulado')], default='no_generado', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('remito', 'Remito'), ('recibo', 'Recibo')], max_length=20),
        ),
    ]
