# Generated by Django 6.1 on 2026-09-03 03:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_facturacliente'),
        ('ventas', '0002_factura_creado_por_usuario_factura_es_remito_manual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='notas',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pedidoonline',
            name='fecha_entrega_estimada',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descuento',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='longitud_corte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longitud de corte en metros (para productos que se cortan)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoonline',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='convertido_a_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_origen', to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('remito', 'Remito'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoonline',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('procesando', 'Procesando'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('local', 'Local'), ('online', 'Online'), ('presupuesto', 'Presupuesto')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
