# Generated by Django 6.1 on 2026-09-03 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_monto_total_facturacliente_monto_original_and_more'),
        ('ventas', '0004_venta_metodo_pago_venta_vendedor_caja_venta_caja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('fecha_entrega_estimada', models.DateField()),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('porcentaje_pendiente', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acopios', to='clientes.cliente')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acopio', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Acopio',
                'verbose_name_plural': 'Acopios',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
