"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t2+v=wxn@=2$i+=f(ptn1=m!docj(-7aqm#&tcmq*64)rue=7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Aceptar cualquier host (para desarrollo local)

# Security settings for Railway
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-67413.up.railway.app',
    'https://*.up.railway.app',
    'http://localhost',
    'http://127.0.0.1',
]

# Configuración para servir archivos estáticos en Railway
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'productos',
    'ventas',
    'clientes',
    'proveedores',
    'reportes',
    'sync',  # Sistema de sincronización local-nube
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

import os
import dj_database_url

# Configuración para Railway (DATABASE_URL proporcionada automáticamente)
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración para Railway - servir archivos estáticos correctamente
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Custom user model
AUTH_USER_MODEL = 'usuarios.Usuario'

# Configuración ARCA (Facturación Electrónica)
ARCA_API_URL = 'https://api.arca.com.ar/v1'  # URL de demostración
ARCA_API_KEY = 'tu_api_key_aqui'  # Reemplazar con API key real
ARCA_CUIT = '20000000000'  # Reemplazar con CUIT real
ARCA_PUNTO_VENTA = '0001'  # Punto de venta para facturación
ARCA_MODO_DEMO = True  # Cambiar a False cuando se tenga cuenta real

# Configuración WhatsApp Business API
WHATSAPP_API_URL = 'https://graph.facebook.com/v17.0'
WHATSAPP_PHONE_NUMBER_ID = 'tu_phone_number_id_aqui'  # Reemplazar con ID real
WHATSAPP_ACCESS_TOKEN = 'tu_access_token_aqui'  # Reemplazar con token real

# Configuración del negocio para instalación local
NOMBRE_NEGOCIO = 'Ferretería Corralón'
DIRECCION_NEGOCIO = 'Dirección del negocio'
TELEFONO_NEGOCIO = 'Teléfono'
LOGO_NEGOCIO = 'logo.png'  # Archivo en static/
CUIT_NEGOCIO = '20-00000000-0'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
