# Generated by Django 6.1 on 2026-09-03 03:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('menudeo', 'Menudeo'), ('mayorista', 'Mayorista'), ('contratista', 'Contratista'), ('obra', 'Obra'), ('promocional', 'Promocional')], default='menudeo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento sobre precio base', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Factor de conversión de unidad base a unidad de venta', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitud_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longitud total en metros (para productos que se cortan)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_cortes',
            field=models.BooleanField(default=False, help_text='Permite venta por longitud (barras, tubos)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida_venta',
            field=models.CharField(default='unidad', help_text='Unidad de venta: unidad, metro, kg, litro, caja', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='unidad', help_text='Unidad base: unidad, metro, kg, litro, caja', max_length=20),
        ),
        migrations.CreateModel(
            name='PrecioLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.listaprecios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_lista', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Precio de Lista',
                'verbose_name_plural': 'Precios de Lista',
                'ordering': ['-vigente_desde'],
                'unique_together': {('producto', 'lista', 'vigente_desde')},
            },
        ),
    ]
