# Generated by Django 6.1 on 2026-09-03 04:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_listaprecios_producto_factor_conversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal'), ('deposito', 'Depósito'), ('taller', 'Taller')], default='deposito', max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='KitProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kit de Producto',
                'verbose_name_plural': 'Kits de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.deposito'),
        ),
        migrations.AddField(
            model_name='producto',
            name='deposito_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.deposito'),
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.kitproducto')),
            ],
            options={
                'verbose_name': 'Item de Kit',
                'verbose_name_plural': 'Items de Kit',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia'), ('ajuste', 'Ajuste'), ('venta', 'Venta')], default='transferencia', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='productos.deposito')),
                ('deposito_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='productos.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='productos.producto')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Stock',
                'verbose_name_plural': 'Transferencias de Stock',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ProductoEquivalente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad de sustitución (1 es el más alto)')),
                ('activo', models.BooleanField(default=True)),
                ('equivalente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustitutos', to='productos.producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalentes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto Equivalente',
                'verbose_name_plural': 'Productos Equivalentes',
                'unique_together': {('producto', 'equivalente')},
            },
        ),
        migrations.CreateModel(
            name='StockDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación específica en el depósito', max_length=100)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_deposito', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Stock por Depósito',
                'verbose_name_plural': 'Stocks por Depósito',
                'unique_together': {('producto', 'deposito')},
            },
        ),
    ]
