# Generated by Django 6.1 on 2026-08-18 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_credito',
            field=models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('moroso', 'Moroso'), ('bloqueado', 'Bloqueado')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_deudor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_remito',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
