# Generated by Django 6.1 on 2026-09-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_facturacliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacliente',
            old_name='monto_total',
            new_name='monto_original',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ajuste_inflacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indice_inflacion_base',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Índice de inflación base para ajuste de saldos', max_digits=10),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='monto_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto ajustado por inflación', max_digits=10, null=True),
        ),
    ]
